development:
  adapter: postgresql
  database: profiles_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: profiles_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  database: profiles_production
  pool: 5
